sfdx/force-app/main/default/objects/Twilio_Media__c/Twilio_Media__c.object-meta.xml
<CustomObject>
    <label>Twilio Media</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Twilio Media Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Twilio Medias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx/force-app/main/default/objects/Twilio_Media__c/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>image/jpeg</fullName>
            </value>
            <value>
                <fullName>image/gif</fullName>
            </value>
            <value>
                <fullName>image/png</fullName>
            </value>
            <value>
                <fullName>image/bmp</fullName>
            </value>
            <value>
                <fullName>text/vcard</fullName>
            </value>
            <value>
                <fullName>text/csv</fullName>
            </value>
            <value>
                <fullName>text/rtf</fullName>
            </value>
            <value>
                <fullName>text/richtext</fullName>
            </value>
            <value>
                <fullName>text/calendar</fullName>
            </value>
            <value>
                <fullName>text/directory</fullName>
            </value>
            <value>
                <fullName>application/pdf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx/force-app/main/default/classes/TwilioMediaServices.cls
public with sharing class TwilioMediaServices {

    private static final Integer HTTP_STATUS_MULTIPLE_CHOICES = 300;
    private static final Integer HTTP_STATUS_SWITCH_PROXY = 306;

    @TestVisible
    private static final Integer HTTP_STATUS_TEMPORARY_REDIRECT = 307;

    private static final Integer HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;

    @TestVisible
    private static final String HTTP_HEADER_LOCATION = 'Location';
    
    private static final String HTTP_METHOD_GET = 'GET';

    /**
     * This method will filter out Twilio Media where 
     * the URL is blank If it's not Blank then it will
     * queue up @future method to fetch data from
     * Twilio.
     */
    public static void getMedia(final List<Twilio_Media__c> tms) {
        for(Twilio_Media__c aTM: tms) {
            if(String.isNotBlank(aTM.URL__c)) {
                getMedia(aTM.Id);
            }
        }
    }

    /**
     * This method will fetch the Media from Twilio and 
     * save it as an attachment.
     */
    @future(callout=true)
    private static void getMedia(final Id tmId) {
        final Twilio_Media__c aTM = [
            SELECT Id, URL__c, Content_Type__c
            FROM Twilio_Media__c 
            WHERE Id =: tmId
        ];
        
        final String url = aTM.URL__c;
        final String contentType = aTM.Content_Type__c;

        Boolean redirect = false;
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();

        req.setMethod('GET');
        req.setEndpoint(url);
        res = http.send(req);

        if(res.getStatusCode() >= HTTP_STATUS_MULTIPLE_CHOICES && 
            res.getStatusCode() <= HTTP_STATUS_TEMPORARY_REDIRECT && 
            res.getStatusCode() != HTTP_STATUS_SWITCH_PROXY) {
            do {
                redirect = false; // reset the value each time
                String redirectURL = res.getHeader(HTTP_HEADER_LOCATION); // get location of the redirect
                if(redirectURL == null) {
                    redirect = false;
                    continue;
                }

                req = new HttpRequest();
                req.setEndpoint(redirectURL);
                req.setMethod(HTTP_METHOD_GET);
                res = http.send(req);

                if(res.getStatusCode() != HTTP_STATUS_INTERNAL_SERVER_ERROR || Test.isRunningTest()) {
                    if(res.getStatusCode() >= HTTP_STATUS_MULTIPLE_CHOICES && 
                        res.getStatusCode() <= HTTP_STATUS_TEMPORARY_REDIRECT && 
                        res.getStatusCode() != HTTP_STATUS_SWITCH_PROXY) {
                        redirect = true;
                    }
                }
            } while (redirect && Limits.getCallouts() != Limits.getLimitCallouts());
        }

        if(res.getBodyAsBlob() != null) {
            TimeZone tz = UserInfo.getTimeZone();
            Attachment att = new Attachment(
                Name = DateTime.now().format(), 
                Body = res.getBodyAsBlob(), 
                ContentType = contentType, 
                ParentId = tmId
            );
            insert att;
        }
    }
}